# ============================================
# Docker Create/Destroy
# --------------------------------------------
# docker compose up -d
# docker compose down -v
# ============================================
version: "3.9"
services:
  client:
    image: nginx:alpine
    container_name: client
    ports:
      - 8090:80
    volumes:
      - ./client:/usr/share/nginx/html
  server:
    image: server
    runtime: io.containerd.wasmedge.v1
    container_name: server
    build:
      context: .
      platforms:
        - wasi/wasm32
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: mysql://root:whalehello@db:3306/mysql
      RUST_BACKTRACE: full
    restart: unless-stopped
  db:
    image: mariadb:10.9
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: whalehello
