# ============================================
# Docker Create/Destroy
# --------------------------------------------
# docker compose -f mariadb.yml up -d
# ocker compose -f mariadb.yml down -v
# ============================================
version: "3.9"
services:
  db:
    image: mariadb:10.9
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: whalehello
